### ISSUE TITLE
Plugin being reported as out of date via discord.

### ISSUE THREAD

**Issue by mysticentity** [Mopsgamer/BetterDiscord-codes#49] opened 2022-09-06 01:39 UTC
When ever discord is reloaded it informs me that the animations plugin is out of date and when I click the red box go to the plugin it has a button to click to update. Doing so installs version 1.3.6.1 then has the blue bar pop up telling me that the animations plugin has an update and in clicking it I get 1.3.8 installed. Not sure if this is an issue with discord but I thought I would report it here.

**Comment by Assassins88** [comment] 2022-09-06 12:39
same her

**Comment by Mopsgamer** [comment] 2023-04-03 15:44
Issue resolved by BetterDiscord.
The issue has been resolved by BetterDiscord for some time.
If there is a problem, it is not caused by the plugin.

**Closed by Mopsgamer** 2023-04-03 15:44 UTC
Labels: bug
